# Generated by Django 4.0.1 on 2022-04-21 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblMAIL_MainMailList',
            fields=[
                ('id', models.CharField(db_column='MAILKEY', max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('MAILInDate', models.DateTimeField(db_column='MAILInDate', default=datetime.date.today, verbose_name='刷入日期')),
                ('MAILSN', models.IntegerField(db_column='MAILSN')),
                ('MAILEditDate', models.DateTimeField(db_column='MAILEditDate', verbose_name='編輯日期')),
                ('MAILFrom', models.CharField(db_column='MAILFrom', max_length=20, verbose_name='寄件單位')),
                ('MAILTo', models.CharField(db_column='MAILTo', max_length=20, verbose_name='收件人')),
                ('MAILGroup', models.CharField(db_column='MAILGroup', max_length=20, verbose_name='收件群組')),
                ('MAILMemo', models.TextField(db_column='MAILMemo', verbose_name='備註')),
                ('MAILTakeDate', models.DateTimeField(db_column='MAILTakeDate', verbose_name='取件日期')),
                ('MAILTakeWN', models.CharField(db_column='MAILTakeWN', max_length=10, verbose_name='取件人工號')),
                ('MAILTakeName', models.CharField(db_column='MAILTakeName', max_length=10, verbose_name='取件人姓名')),
                ('MAILTakeMemo', models.TextField(db_column='MAILTakeMemo', verbose_name='取件備註')),
                ('MAILFlag', models.IntegerField(db_column='MAILFlag')),
            ],
            options={
                'verbose_name': '郵件登錄',
                'db_table': 'tblMAIL_MainMailList',
                'ordering': ['-id'],
            },
        ),
    ]
