# Generated by Django 4.0.1 on 2022-04-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRemind',
            fields=[
                ('id', models.CharField(db_column='RemindId', max_length=100, primary_key=True, serialize=False)),
                ('ARName', models.CharField(db_column='Name', max_length=100, verbose_name='名稱')),
                ('ARContent', models.CharField(db_column='AlertContent', max_length=100, verbose_name='內容')),
                ('ARTime', models.CharField(db_column='Requests', max_length=100, verbose_name='發送時間')),
                ('IsActive', models.BooleanField(db_column='IsActive', verbose_name='執行否')),
            ],
            options={
                'verbose_name': 'Alert',
                'db_table': 'AlertRemind',
                'ordering': ['ARName'],
            },
        ),
        migrations.CreateModel(
            name='AlertReport',
            fields=[
                ('AReportid', models.CharField(db_column='AlertReportId', max_length=50, primary_key=True, serialize=False)),
                ('ARportName', models.CharField(db_column='Name', max_length=50)),
                ('ARportContent', models.TextField(db_column='AlertContent')),
            ],
            options={
                'verbose_name': 'Alert 郵件設定',
                'db_table': 'AlertReport',
            },
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('code', models.CharField(db_column='code', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
            ],
            options={
                'verbose_name': '部門',
                'db_table': 'Department',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('code', models.CharField(db_column='code', max_length=10, primary_key=True, serialize=False)),
                ('cnname', models.CharField(db_column='cnname', max_length=20)),
            ],
            options={
                'db_table': 'Employee',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AlertSet',
            fields=[
                ('ASid', models.CharField(db_column='AlertSetId', max_length=50, primary_key=True, serialize=False)),
                ('ASsql', models.TextField(db_column='SourceSql', verbose_name='SQL')),
                ('ADRid', models.ForeignKey(db_column='RemindId', on_delete=django.db.models.deletion.DO_NOTHING, to='hrbasic.alertremind')),
                ('ASRepportid', models.ForeignKey(db_column='AlertReportId', on_delete=django.db.models.deletion.DO_NOTHING, to='hrbasic.alertreport')),
            ],
            options={
                'verbose_name': 'Alert Sql',
                'db_table': 'AlertSet',
            },
        ),
    ]
