# Generated by Django 4.0.1 on 2022-04-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.CharField(db_column='id', max_length=10, primary_key=True, serialize=False, verbose_name='工號')),
                ('userName', models.CharField(db_column='userName', max_length=10, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '員工資料',
                'db_table': 'Users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('organizationUnitName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'OrganizationUnit',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TYHR11',
            fields=[
                ('formSerialNumber', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('txt_code', models.CharField(db_column='txt_code', max_length=6, verbose_name='預取工號')),
                ('txt_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('drp_status', models.CharField(choices=[('W', '待報到'), ('Y', '已報到'), ('X', '取消報到')], default='W', max_length=1, verbose_name='人員狀態')),
                ('txt_note', models.TextField(blank=True, verbose_name='備註')),
                ('date_date', models.DateField(verbose_name='預計報到日')),
                ('dia_dep', models.ForeignKey(db_column='dia_dep', on_delete=django.db.models.deletion.CASCADE, to='bpm.organizationunit', verbose_name='預計部門')),
            ],
            options={
                'verbose_name': '預取工號',
                'db_table': 'TYHR11',
            },
        ),
        migrations.CreateModel(
            name='TYAD02',
            fields=[
                ('formSerialNumber', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='表單序號')),
                ('txt_notemployee', models.CharField(db_column='txt_notemployee', max_length=20, verbose_name='非員工用餐人')),
                ('drop_category', models.CharField(choices=[('素食便當', '素食便當'), ('非豬葷便當', '非豬葷便當'), ('取消申請', '取消申請')], default='W', max_length=10, verbose_name='申請類別')),
                ('date_adbegin', models.DateField(db_column='date_adbegin', verbose_name='生效日')),
                ('date_adenddate', models.DateField(db_column='date_adenddate', verbose_name='截止日')),
                ('text_applynote', models.TextField(blank=True, verbose_name='申請備註')),
                ('date_begin', models.DateField(db_column='date_begin', verbose_name='希望生效日')),
                ('date_enddate', models.DateField(db_column='date_enddate', verbose_name='希望截止日')),
                ('text_adnote', models.TextField(blank=True, verbose_name='行政備註')),
                ('Dia_user', models.ForeignKey(db_column='Dia_user', on_delete=django.db.models.deletion.DO_NOTHING, to='bpm.emp', verbose_name='申請人')),
            ],
            options={
                'verbose_name': '特殊餐申請',
                'db_table': 'TYAD02',
            },
        ),
    ]
