# Generated by Django 4.0.1 on 2022-04-21 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import rec.models.Recruit_Request


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrbasic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerValue',
            fields=[
                ('ID', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ValueType', models.IntegerField(default=4)),
                ('StringValue1', models.CharField(max_length=50, verbose_name='待辦說明')),
                ('StringValue2', models.CharField(choices=[('G1', '新進繳交'), ('G2', '發放品項'), ('G3', '行政待辦')], max_length=5, verbose_name='待辦類別')),
                ('StringValue3', models.CharField(blank=True, max_length=50, verbose_name='份數與必要非必要')),
            ],
            options={
                'verbose_name': '待辦事項基礎設定',
                'db_table': 'ServerValue',
            },
        ),
        migrations.CreateModel(
            name='Recruit_Request',
            fields=[
                ('ID', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('VerificationCode', models.IntegerField(default=rec.models.Recruit_Request.random_int, verbose_name='驗證碼')),
                ('RequestTime', models.DateField(default=datetime.date.today, verbose_name='接收日期')),
                ('RecruitRequestType', models.IntegerField(choices=[(0, '0:人力銀行'), (1, '徵才活動'), (2, '親友介紹'), (1000, '其他')], default=0, verbose_name='來源類型')),
                ('RecruitRequestComment', models.CharField(blank=True, max_length=255, verbose_name='履歷編號')),
                ('CandidatesName', models.CharField(max_length=20, verbose_name='面試人姓名')),
                ('JobName', models.CharField(max_length=20, verbose_name='應徵職務')),
                ('PhoneNumber', models.CharField(max_length=15, verbose_name='聯絡電話')),
                ('CandidatesMail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('Remarks', models.TextField(blank=True, max_length=255, verbose_name='備註')),
                ('InterviewTime', models.DateTimeField(verbose_name='面試日期')),
                ('RecruitStatus', models.IntegerField(choices=[(1, '無法聯絡上本人'), (2, '答應參加面試'), (3, '考慮中'), (4, '婉拒'), (8, '未依約面試'), (9, '取消面試'), (10, '未錄取 '), (12, '基本資料卡填寫完成'), (13, '完成報到資料填寫'), (14, '完成任用單')], default=2, verbose_name='狀態')),
                ('IsFinished', models.IntegerField(choices=[(0, '未結案'), (1, '結案')], verbose_name='結案否')),
                ('RequestDep', models.ForeignKey(db_column='RequestDep', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='hrbasic.dep', verbose_name='需求部門')),
            ],
            options={
                'verbose_name': '招募登錄',
                'db_table': 'Recruit_Request',
                'ordering': ['-RecruitStatus'],
            },
        ),
        migrations.CreateModel(
            name='Recruit_CheckList',
            fields=[
                ('ID', models.IntegerField(db_column='ID', default=1, primary_key=True, serialize=False)),
                ('checked', models.BooleanField(db_column='checked', default=True)),
                ('CheckID', models.ForeignKey(db_column='CheckID', on_delete=django.db.models.deletion.DO_NOTHING, to='rec.servervalue')),
                ('RequestID', models.ForeignKey(db_column='RequestID', on_delete=django.db.models.deletion.DO_NOTHING, to='rec.recruit_request')),
            ],
            options={
                'verbose_name': '報到人員對應待辦狀態',
                'db_table': 'Recruit_CheckList',
            },
        ),
    ]
