# Generated by Django 2.1.15 on 2021-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='部門編號')),
                ('name', models.CharField(max_length=20, verbose_name='部門名稱')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
