# Generated by Django 4.0.10 on 2024-01-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='制服編號')),
                ('name', models.CharField(max_length=20, verbose_name='制服名稱')),
            ],
            options={
                'db_table': 'clothing',
            },
        ),
        migrations.AlterField(
            model_name='dep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
