# Generated by Django 4.0.10 on 2024-01-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='closestoack',
            fields=[
                ('close_sn', models.AutoField(db_column='close_sn', primary_key=True, serialize=False)),
                ('close_id', models.CharField(choices=[('TY制服_長黑', 'TY制服_長黑'), ('TY制服_短黑', 'TY制服_短黑'), ('TY制服_短白', 'TY制服_短白')], db_column='close_id', max_length=50, verbose_name='制服類型')),
                ('close_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], db_column='close_size', max_length=5, verbose_name='制服尺寸')),
                ('close_number', models.IntegerField(db_column='close_number', verbose_name='數量')),
                ('close_employee', models.CharField(db_column='close_employee', max_length=10, verbose_name='登錄員工')),
            ],
            options={
                'verbose_name': '制服庫存管理',
                'db_table': 'close_stock',
            },
        ),
    ]
