"""
Django settings for toyo project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z+u5z&41swb9r2a!zfbn7oe=f7+m@w@5p3(0&v_hd!7wp$0s01'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.113.102','127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'hrbasic.apps.HrbasicConfig',
    'bpm.apps.BpmConfig',
    'rec.apps.RecConfig',
    'web254',
    'timdb',
    'form',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_tables2',
    'widget_tweaks',
    'bootstrap_datepicker_plus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'toyo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'toyo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
     'hrbasic': {
         #'ENGINE': 'sql_server.pyodbc',
         'ENGINE': 'mssql',
         'NAME': 'HRMDB',
         'USER': 'hr',
         'PASSWORD': 'hr_2021347',
         'HOST': '192.168.1.66',
         'PORT': '1433',
         'OPTIONS': {
             'driver':'ODBC Driver 17 for SQL Server',
         },

    },
    'bpm': {
        'ENGINE': 'mssql',
        'NAME': 'EFGP',
        'USER': 'hr',
        'PASSWORD': 'hr_2021347',
        'HOST': '192.168.1.66',
        'PORT': '1433',
        'OPTIONS': {
            'driver':'ODBC Driver 17 for SQL Server',
        },
    },
    'rec': {
        'ENGINE': 'mssql',
        'NAME': 'CommonDB',
        'USER': 'hr',
        'PASSWORD': 'hr_2021347',
        'HOST': '192.168.110.220',
        'PORT': '1433',
        'OPTIONS': {
            'driver':'ODBC Driver 17 for SQL Server',
        },
    },
    'web254': {
        'ENGINE': 'mssql',
        'NAME': 'toyo_web',
        'USER': 'hr',
        'PASSWORD': 'hr_2021347',
        'HOST': '192.168.1.254',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'timdb': {
        'ENGINE': 'mssql',
        'NAME': 'TIM_DB',
        'USER': 'hr',
        'PASSWORD': 'hr_2021347',
        'HOST': '192.168.1.254',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'form': {
        'ENGINE': 'mssql',
        'NAME': 'FORM',
        'USER': 'hr',
        'PASSWORD': 'hr_2021347',
        'HOST': '192.168.1.254',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'oracle': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'TY_TEST',
        'USER': 'ty_test',
        'PASSWORD': 'ty_test',
        'HOST': '192.168.1.61',
        'PORT': '1433',

    },
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 路由配對
DATABASE_APPS_MAPPING = {
    'hrbasic': 'hrbasic',
    'rec': 'hrbasic',
    'rec': 'rec',
    'bpm': 'bpm',
    'timdb': 'timdb',
    'web254': 'web254',
    'form': 'form',
}

DATABASE_ROUTERS = ['toyo.database_router.DatabaseAppsRouter']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}